spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://localhost:5432/pl-db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.ddl-auto: validate


jwt:
  tokenPrefix: Bearer
  header: Authorization
  key: q3t6w9z$C&F)J@NcQfTjWnZr4u7x!A%D*G-KaPdSgUkXp2s5v8y/B?E(H+MbQeTh
  expiresAfter: 180000000

queue:
  battery-registration: q.battery-registration

statistics:
  url: http://localhost:8082/statistics/api

springdoc:
  swagger-ui:
    path: /v3/swagger-ui
    urls-primary-name: one
    enabled: true

  api-docs:
    path: /v3/api-docs
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics