spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pl-db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.ddl-auto: validate


