spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pl-db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.ddl-auto: validate


jwt:
  tokenPrefix: Bearer
  header: Authorization
  key: q3t6w9z$C&F)J@NcQfTjWnZr4u7x!A%D*G-KaPdSgUkXp2s5v8y/B?E(H+MbQeTh
  expiresAfter: 180000000
