apiVersion: apps/v1
kind: Deployment
metadata:
  name: pl-gateway-dep  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pla
      module: gateway
  template:
    metadata:
      labels:
        app: pla
        module: gateway
    spec:
      containers:
        - name: pla-gateway
          image: ruhshan/pla-gateway
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: application-config
---
apiVersion: v1
kind: Service
metadata:
  name: pl-gateway-svc # Sets service name
  labels:
    app: pla # Labels and Selectors
    module: gateway
spec:
  type: NodePort # Sets service type
  ports:
    - port: 8080 # Sets port to run the postgres application
  selector:
    app: pla
    module: gateway