apiVersion: v1
kind: Service
metadata:
  name: rabbitmq # Sets service name
  labels:
    app: rabbitmq # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - name: service
      port: 5672
    - name: admin
      port: 15672
  selector:
    app: rabbitmq