apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pla
      module: redis
  template:
    metadata:
      labels:
        app: pla
        module: redis
    spec:
      containers:
        - name: redis
          image: redis
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis # Sets service name
  labels:
    app: pla
    module: redis # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: 6379
  selector:
    app: pla
    module: redis